# Site settings
title: Noah Lackstein
email: noah@lackstein.com
description: > # this means to ignore newlines until "baseurl:"
  Studying Computer Science and Finance at McGill University in Montreal
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lackstein.com" # the base hostname & protocol for your site
twitter_username: lackstein
github_username:  lackstein

# Build settings
markdown: kramdown
